Creating basic functionality to connect to Discord API, work in progress.
ATN-Development/erebus pull request #13
Opened 2021-10-26 18:10 UTC by NotReallyEight

- [x] Connect function.
- [x] Identify.
- [x] Interval to send heartbeat.
- [ ] Handling all kind of [events](https://discord.com/developers/docs/topics/gateway#commands-and-events-gateway-events) from Discord through OP Code.
- [x] Make the actual resume a function, so it can be used throughout the code.
- [x] Export Private Channel, Guild Channel from `structures/index.ts`.
- [ ] Listen to 'close' event in WebSocket, and handle close code 1006, as Connection closed abnormally
- [x] Update method for all the classes.
- [x] Make a `AnyGuildChannel` type alias with all the guild channel type definitions
- [x] Store `seq` as the `s` property in payloads, if it does not exist or it is null, then make it the last one it received.

2021-11-13 19:29 UTC, NotReallyEight commented
Need to uninstall un pkg I installed by fault.

2021-11-14 14:01 UTC, DTrombett commented on src/Client.ts
> +	seq: number = 0;
```suggestion
	seq = 0;
```

2021-11-14 17:57 UTC, DTrombett requested changes

2021-11-14 17:57 UTC, DTrombett commented on src/structures/PrivateChannel.ts
> +} from "../../node_modules/discord-api-types/v9";
Blame autoimport
```suggestion
} from "discord-api-types/v9";
```

2021-11-14 17:57 UTC, DTrombett commented on src/structures/PrivateChannel.ts
> +	constructor(payload: APIChannel, client: Client) {
🧹
```suggestion
	constructor(client: Client, payload: APIChannel) {
```

2021-11-14 17:57 UTC, DTrombett commented on src/structures/PrivateChannel.ts
> +import { Channel } from "./Channel";
```suggestion
import Channel from "./Channel";
```

2021-11-14 17:57 UTC, DTrombett commented on src/structures/PrivateChannel.ts
> +			(recipient) => new User(recipient, client)
```suggestion
			(recipient) => new User(client, recipient)
```

2021-11-14 17:57 UTC, DTrombett commented on src/structures/User.ts
> +	constructor(payload: APIUser, client: Client) {
```suggestion
	constructor(client: Client, payload: APIUser) {
```

2021-11-18 07:07 UTC, DTrombett commented
TODO:

- [ ] Add new Application properties (discordjs/discord-api-types#239)

2021-12-04 19:13 UTC, NotReallyEight commented
I think, we should change this Pull Request, and move it to other separate pull requests. This PR is getting just way too big and it already does what it needs to do. I will merge it soon.

2021-12-04 19:19 UTC, merged